package api_test

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/takutakahashi/memory-server/internal/api"
	"github.com/takutakahashi/memory-server/internal/auth"
)

// fakeUserStore is an in-memory implementation of auth.UserStorer for tests.
type fakeUserStore struct {
	users     map[string]*auth.User
	orgTokens map[string]*auth.OrgToken
}

func newFakeStore() *fakeUserStore {
	return &fakeUserStore{
		users:     make(map[string]*auth.User),
		orgTokens: make(map[string]*auth.OrgToken),
	}
}

func (f *fakeUserStore) GetOrgToken(_ context.Context, token string) (*auth.OrgToken, error) {
	t, ok := f.orgTokens[token]
	if !ok {
		return nil, fmt.Errorf("%w: org token", auth.ErrNotFound)
	}
	return t, nil
}

func (f *fakeUserStore) PutUser(_ context.Context, u *auth.User) error {
	cp := *u
	f.users[u.UserID] = &cp
	return nil
}

func (f *fakeUserStore) GetUser(_ context.Context, userID string) (*auth.User, error) {
	u, ok := f.users[userID]
	if !ok {
		return nil, fmt.Errorf("%w: user %s", auth.ErrNotFound, userID)
	}
	return u, nil
}

func (f *fakeUserStore) GetUserByToken(_ context.Context, token string) (*auth.User, error) {
	for _, u := range f.users {
		if u.Token == token {
			cp := *u
			return &cp, nil
		}
	}
	return nil, fmt.Errorf("%w: user token", auth.ErrNotFound)
}

// helpers

func newMux(store *fakeUserStore) *http.ServeMux {
	mux := http.NewServeMux()
	userSrv := api.NewUserServer(store)
	userSrv.RegisterUserRoutes(mux, auth.OrgTokenAuth(store))
	return mux
}

func bodyJSON(t *testing.T, v any) *bytes.Buffer {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return bytes.NewBuffer(b)
}

func do(mux *http.ServeMux, method, path, orgToken string, body *bytes.Buffer) *httptest.ResponseRecorder {
	if body == nil {
		body = bytes.NewBuffer(nil)
	}
	req := httptest.NewRequest(method, path, body)
	if orgToken != "" {
		req.Header.Set("Authorization", "Bearer "+orgToken)
	}
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	return w
}

// -------------------------------------------------------------------------
// Tests
// -------------------------------------------------------------------------

func TestCreateUser_NoOrgToken_Returns401(t *testing.T) {
	store := newFakeStore()
	mux := newMux(store)

	w := do(mux, "POST", "/api/v1/users", "", bodyJSON(t, map[string]string{"user_id": "alice"}))
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d: %s", w.Code, w.Body.String())
	}
}

func TestCreateUser_InvalidOrgToken_Returns401(t *testing.T) {
	store := newFakeStore()
	mux := newMux(store)

	w := do(mux, "POST", "/api/v1/users", "bad-token", bodyJSON(t, map[string]string{"user_id": "alice"}))
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d: %s", w.Code, w.Body.String())
	}
}

func TestCreateUser_NewUser_AutoGeneratedToken(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	mux := newMux(store)

	w := do(mux, "POST", "/api/v1/users", "org-secret", bodyJSON(t, map[string]string{
		"user_id":     "alice",
		"description": "Alice",
	}))
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var user auth.User
	if err := json.NewDecoder(w.Body).Decode(&user); err != nil {
		t.Fatal(err)
	}
	if user.UserID != "alice" {
		t.Errorf("user_id = %q, want alice", user.UserID)
	}
	if user.Token == "" {
		t.Error("token should be auto-generated, got empty string")
	}
	if user.OrgID != "my-org" {
		t.Errorf("org_id = %q, want my-org", user.OrgID)
	}
}

func TestCreateUser_NewUser_CallerSpecifiedToken(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	mux := newMux(store)

	w := do(mux, "POST", "/api/v1/users", "org-secret", bodyJSON(t, map[string]any{
		"user_id": "bob",
		"token":   "my-custom-token",
	}))
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var user auth.User
	if err := json.NewDecoder(w.Body).Decode(&user); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if user.Token != "my-custom-token" {
		t.Errorf("token = %q, want my-custom-token", user.Token)
	}
}

func TestCreateUser_UpdateExisting_Returns200(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	store.users["alice"] = &auth.User{
		UserID:    "alice",
		Token:     "old-token",
		OrgID:     "my-org",
		CreatedAt: time.Now().Add(-24 * time.Hour),
	}
	mux := newMux(store)

	w := do(mux, "POST", "/api/v1/users", "org-secret", bodyJSON(t, map[string]any{
		"user_id": "alice",
		"token":   "new-token",
	}))
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var user auth.User
	if err := json.NewDecoder(w.Body).Decode(&user); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if user.Token != "new-token" {
		t.Errorf("token = %q, want new-token", user.Token)
	}
	// created_at should be preserved
	if user.CreatedAt.IsZero() {
		t.Error("created_at should be preserved")
	}
	if time.Since(user.CreatedAt) < time.Hour {
		t.Error("created_at should be the original old value, not now")
	}
}

func TestCreateUser_AutoGenerateUserID(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	mux := newMux(store)

	// No user_id in request
	w := do(mux, "POST", "/api/v1/users", "org-secret", bodyJSON(t, map[string]string{}))
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var user auth.User
	if err := json.NewDecoder(w.Body).Decode(&user); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if user.UserID == "" {
		t.Error("user_id should be auto-generated")
	}
}

func TestGetUser_Found(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	store.users["alice"] = &auth.User{UserID: "alice", Token: "tok", OrgID: "my-org", CreatedAt: time.Now()}
	mux := newMux(store)

	w := do(mux, "GET", "/api/v1/users/alice", "org-secret", nil)
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", w.Code, w.Body.String())
	}
	var user auth.User
	if err := json.NewDecoder(w.Body).Decode(&user); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if user.UserID != "alice" {
		t.Errorf("user_id = %q, want alice", user.UserID)
	}
}

func TestGetUser_NotFound(t *testing.T) {
	store := newFakeStore()
	store.orgTokens["org-secret"] = &auth.OrgToken{Token: "org-secret", OrgID: "my-org", CreatedAt: time.Now()}
	mux := newMux(store)

	w := do(mux, "GET", "/api/v1/users/nobody", "org-secret", nil)
	if w.Code != http.StatusNotFound {
		t.Fatalf("expected 404, got %d: %s", w.Code, w.Body.String())
	}
}

// Ensure fakeUserStore satisfies the interface at compile time.
var _ auth.UserStorer = (*fakeUserStore)(nil)
