{{- if and (not .Values.existingSecret) (or .Values.aws.accessKeyId .Values.aws.secretAccessKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memory-server.fullname" . }}-aws
  labels:
    {{- include "memory-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
