{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "memory-server.serviceAccountName" . }}
  labels:
    {{- include "memory-server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.aws.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
